server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Atharv-Hule-33/recruitx-config
          default-label: main
          clone-on-start: true
